sudo: required
services:
  - docker

before_install:
  - docker build -t shayansolutions/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shayansolutions/react-test npm test -- --coverage

after_success:
  - docker build -t shayansolutions/multi-client ./client
  - docker build -t shayansolutions/multi-nginx ./nginx
  - docker build -t shayansolutions/multi-server ./server
  - docker build -t shayansolutions/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shayansolutions/multi-client
  - docker push shayansolutions/multi-nginx
  - docker push shayansolutions/multi-server
  - docker push shayansolutions/multi-wprker

deploy:
  provider: elasticbeanstalked
  region: us-east-2
  app: multi-docker  
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-853363226885
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  